import { useEffect, useState } from 'react'
import { api, money } from '../api'
import { PageHeading, Panel, DataTable, Badge, Loading, Modal } from '../components'
export default function Approvals({currency}:{currency:string}){
 const [rows,setRows]=useState<any[]|null>(null),[dialog,setDialog]=useState<any>(null),[comment,setComment]=useState('')
 const load=()=>api('/approvals?status=pending').then(setRows)
 useEffect(()=>{load()},[])
 async function decide(){if(!dialog)return;if(dialog.kind==='reject'&&!comment.trim())return;await api('/approvals/'+dialog.row.id+'/'+dialog.kind,{method:'POST',body:JSON.stringify({comment})});setDialog(null);setComment('');load()}
 if(!rows)return <Loading/>
 return <div><PageHeading eyebrow="Management control" title="Approval Center" sub="Review sensitive transactions before they affect purchasing, inventory or restaurant operations."/><Panel title="Pending approvals" sub={rows.length+' waiting for management'}><DataTable head={['Priority','Reference','Section','Request','Requested by','Amount','Action']} rows={rows.map(a=>[a.priority==='urgent'?<Badge tone="red">URGENT</Badge>:<Badge>Normal</Badge>,<b>{a.reference_no||'#'+a.id}</b>,a.section,a.title,a.requested_by_name||'-',a.amount!=null?money(a.amount,currency):'-',<div className="flex gap-2"><button onClick={()=>setDialog({row:a,kind:'reject'})} className="rounded-lg border border-red-200 text-red-600 px-3 py-1.5 text-xs font-bold">Reject</button><button onClick={()=>setDialog({row:a,kind:'approve'})} className="rounded-lg bg-slate-950 text-white px-3 py-1.5 text-xs font-bold">Approve</button></div>])}/></Panel>{dialog&&<Modal title={dialog.kind==='approve'?'Approve request':'Reject request'} onClose={()=>setDialog(null)}><p className="text-sm text-slate-500">{dialog.row.title}</p><textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-4 w-full min-h-28 rounded-xl border border-slate-200 p-3 outline-none focus:ring-4 focus:ring-emerald-100" placeholder={dialog.kind==='reject'?'Reason for rejection (required)':'Management comment (optional)'}/><button onClick={decide} className={'mt-4 w-full rounded-xl py-3 font-bold text-white '+(dialog.kind==='reject'?'bg-red-600':'bg-slate-950')}>{dialog.kind==='reject'?'Reject Request':'Approve Request'}</button></Modal>}</div>
}
