import { useMemo, useState } from 'react'
import {
  ArrowLeft, Banknote, BarChart3, Boxes, Building2, ChefHat, ClipboardCheck, FileText,
  HelpCircle, Landmark, Package, Printer, Search, Settings, ShieldCheck, ShoppingCart,
  Store, Truck, UserRoundCog, UtensilsCrossed
} from 'lucide-react'
import { MauzoLogo } from '../Brand'

type Doc={
 id:string;title:string;icon:any;purpose:string;
 actions:string[];fields:string[];rules:string[];access:string;troubleshooting:string[]
}

const docs:Doc[]=[
 {id:'overview',title:'System Overview',icon:FileText,purpose:'Understand how MauzoPOS separates daily operations from management and control.',actions:['Operations: Sell / Checkout, Orders, Kitchen, Tables, Sales History, Customers and My Shift.','Management: Approvals, Products, Inventory, Purchasing, Expenses, Accounting, Reports, Users, Branches and Settings.','Use the business/branch context shown in the system before posting transactions.'],fields:['Business','Branch','Terminal / counter','User / role','Active shift'],rules:['Use your own account.','Do not bypass an operational workflow with manual accounting or stock changes.','Use generated documents rather than screenshots for receipts, KOTs and reports.'],access:'Available modules depend on role, branch assignment and enabled business modules.',troubleshooting:['If a module is missing, check role, permissions, branch assignment and enabled modules.','If a transaction seems missing, search by its source reference before recreating it.']},
 {id:'sales',title:'Sell / Checkout',icon:ShoppingCart,purpose:'Create customer sales and capture the real payment method.',actions:['Add items by search, SKU or barcode.','Set quantity and approved discounts/FOC.','Select customer when needed.','Take cash, mobile money, card, bank or split payment.','Complete sale and generate receipt.'],fields:['Product','Quantity','Price','Discount / FOC reason','Customer','Payment method','Tendered amount'],rules:['An open shift may be required for cashier sales.','Payment method must match how the customer actually paid.','Do not recreate a sale just to print another receipt.'],access:'Usually Cashier, Manager, Owner or other permitted sales roles.',troubleshooting:['Sale blocked: check shift, stock, approval and payment source.','Wrong payment: investigate the transaction before any correction/refund.']},
 {id:'restaurant',title:'Restaurant / Tables',icon:UtensilsCrossed,purpose:'Manage dine-in tables, orders, takeaway, delivery, reservations and service status.',actions:['Open or continue the correct table order.','Add items, quantities and notes.','Send items to Kitchen/Bar.','Track service status.','Generate bill and receive payment.','Reset table when service is complete.'],fields:['Table / area','Guest / party size','Order type','Items','Kitchen notes','Payment','Delivery details where used'],rules:['Do not open duplicate active orders for one table.','Add later items to the existing open order.','Close an order only after payment or approved outstanding handling.'],access:'Waiter, Restaurant Manager, Owner and other configured roles.',troubleshooting:['Missing KOT: confirm item was sent and station mapping exists.','Table stuck occupied: inspect open order and cleaning status.']},
 {id:'kitchen',title:'Kitchen / Bar',icon:ChefHat,purpose:'Process production tickets from new to ready/served.',actions:['Read live ticket and notes.','Start preparation.','Mark Ready.','Mark Served where used.','Rush genuinely urgent tickets.','Reprint KOT when needed.'],fields:['Ticket number','Order / table','Station','Items','Quantity','Notes','Timer','Status'],rules:['Status should reflect real preparation progress.','Do not create a duplicate order to reprint a ticket.'],access:'Kitchen, Bar, Restaurant Manager and authorised management roles.',troubleshooting:['No ticket: check station/menu mapping and whether the order was sent.','Wrong status: use the order/ticket history before changing source data.']},
 {id:'products',title:'Products',icon:Boxes,purpose:'Define what the business sells or tracks before stock movements happen.',actions:['Create product.','Set price and cost.','Choose category.','Set opening stock when stock already exists.','Choose restock method.','Set reorder/refill alert.','Enable batch/expiry where needed.'],fields:['Name','Category','SKU / barcode','Cost','Selling price','Opening stock','Opening location','Restock method','Reorder level','Suppliers','Batch / expiry requirement'],rules:['Product is the item definition; Stock is the current quantity.','Opening stock is only for the quantity already present when creating the product.','Later quantity changes belong in Inventory or Purchasing, not Product edit.'],access:'Owner, Administrator, Manager, Storekeeper and other configured roles.',troubleshooting:['Stock field disabled on edit is intentional; use Inventory.','Wrong restock button: edit the product restock method.']},
 {id:'inventory',title:'Inventory / Stock',icon:Store,purpose:'Control how much stock exists, where it is and why it changed.',actions:['Add / Refill Stock for internally prepared/produced items.','Receive Delivery for supplier stock.','Move Stock between locations.','Count Stock physically.','Correct Stock for unexpected differences.','Assign batch/expiry to stock already on hand.','Review Stock History.'],fields:['Location','Product','On hand','Restock method','Quantity','Reorder alert','Average cost','Stock value','Reason / reference'],rules:['Made here → Add / Refill Stock.','Supplier brought it → Receive Delivery.','Unexpected difference → Correct Stock.','Batch assignment does not increase stock.','Physical count should be posted only after actual quantities are entered.'],access:'Storekeeper, Manager, Owner and inventory-permitted roles.',troubleshooting:['Quantity wrong: inspect Stock History first.','Cannot refill: confirm product restock method includes Prepared.','Supplier item: use Purchasing rather than stock correction.']},
 {id:'purchasing',title:'Purchasing & Receiving',icon:Truck,purpose:'Order stock from suppliers and receive deliveries into inventory with cost and accounting traceability.',actions:['Create Purchase Order.','Submit/approve where required.','Receive actual delivered quantities.','Enter lot/expiry where required.','Post Goods Receipt.','Return goods to supplier when needed.'],fields:['Supplier','Branch / location','Product','Ordered quantity','Received quantity','Outstanding quantity','Unit cost','Batch / lot','Expiry date'],rules:['Creating a Purchase Order does not increase stock.','Only Goods Receipt increases supplier-delivered stock.','Do not receive more than the outstanding quantity.'],access:'Storekeeper, Purchasing roles, Managers, Accountants and authorised users.',troubleshooting:['Cannot receive: check PO status/approval and outstanding quantity.','Expiry-required item: enter batch and expiry before posting.']},
 {id:'suppliers',title:'Suppliers',icon:Package,purpose:'Maintain who the business buys from and link purchasing activity to the right supplier.',actions:['Create supplier.','Maintain contact/payment details.','Link products.','Review supplier purchasing/returns/payments.'],fields:['Supplier name','Phone / email','Payment details','Linked products'],rules:['Avoid duplicate supplier records.','Supplier deliveries should enter stock through Purchasing.'],access:'Management, Purchasing, Storekeeper and permitted accounting roles.',troubleshooting:['Duplicate supplier: search before creating.','Missing supplier product: update product/supplier link.']},
 {id:'shifts',title:'Shifts & Cash Drawer',icon:Banknote,purpose:'Explain every unit of physical cash from opening to close.',actions:['Open Shift.','Add Float.','Pay Out.','Cash Drop / Deposit.','Review Expected Cash.','Count Actual Cash.','Close Shift.'],fields:['Opening cash','Cash sales','Cash movements','Expected cash','Actual cash','Variance','Closing note'],rules:['Opening cash must be the physical amount in the drawer.','Cash expenses/payouts must be recorded.','Do not use cash movements to hide unrelated errors.'],access:'Cashiers and authorised supervisors/managers/accountants.',troubleshooting:['Variance: review opening cash, cash sales, payouts, drops and deposits.','Cannot close: resolve pending or required shift conditions first.']},
 {id:'expenses',title:'Expenses & Allowances',icon:ClipboardCheck,purpose:'Record business money leaving the business with payee and payment-source traceability.',actions:['Create expense.','Select category/account.','Record payee or employee.','Choose actual payment source.','Attach evidence.','Approve controlled payout where required.'],fields:['Reference','Date','Branch / counter','Category','Payee','Description','Expense account','Payment method/source','Amount','Evidence'],rules:['Payment source must match how money actually left the business.','Save once; Mauzo posts linked operational/accounting records automatically.'],access:'Managers, Accountants, Owners and other authorised roles.',troubleshooting:['Cash expense not matching drawer: inspect active shift and cash movement.','Wrong account/source: trace source transaction before correction.']},
 {id:'approvals',title:'Approvals',icon:ShieldCheck,purpose:'Provide controlled authorisation for sensitive transactions.',actions:['Review pending request.','Inspect source details.','Approve justified request.','Reject incorrect request.'],fields:['Requester','Branch','Source reference','Action type','Reason','Amount / items','Approver','Decision'],rules:['Approver must be the real person authorising the action.','Never share manager credentials.'],access:'Configured managers/owners/approvers.',troubleshooting:['No approval shown: verify approval rule and assigned approver.','Request incorrect: reject and correct the source transaction.']},
 {id:'accounting',title:'Accounting',icon:Landmark,purpose:'Review financial postings generated from operations and make authorised accounting adjustments.',actions:['Review journals.','Review account balances.','Review financial statements.','Trace source transaction.','Create manual journal only when necessary.','Run inventory/account reconciliation.'],fields:['Journal','Account','Debit / credit','Branch','Source module','Source reference','Description','Posting date'],rules:['Operational workflows already post accounting automatically.','Do not duplicate a sale, purchase, expense, refund or stock transaction with a manual journal.'],access:'Accountant, Owner, Administrator, Auditor or roles with accounting permission.',troubleshooting:['Unexpected balance: trace journal source before manual correction.','Inventory difference: use Inventory vs Accounts reconciliation.']},
 {id:'reports',title:'Reports & Analytics',icon:BarChart3,purpose:'View source-level data and export the same filtered results.',actions:['Choose report.','Set From, To and Branch.','Generate on screen.','Review KPIs and rows.','Download Excel / CSV / PDF.'],fields:['Report type','From','To','Branch','Summary KPIs','Detailed records'],rules:['Choose the report before date/branch filters.','Exports should match the generated filters.','Use Download PDF rather than browser Print.'],access:'Depends on reporting/accounting permissions and role.',troubleshooting:['Empty report: check date/branch filter.','Export issue: regenerate once and confirm session/download permission.']},
 {id:'staff',title:'Users, Roles & Attendance',icon:UserRoundCog,purpose:'Control who can use MauzoPOS, where they can work and what they can do.',actions:['Create user.','Assign role(s).','Assign branch access.','Configure Quick PIN where used.','Review permissions.','Clock in/out where enabled.','Disable access when staff leave.'],fields:['Name','Email','Role','Branch assignment','Quick PIN','Permission matrix','Staff status'],rules:['Least access necessary is preferred.','Do not share accounts or Quick PINs.'],access:'Owner, Administrator and staff-management permissions.',troubleshooting:['Module missing: check role/permission/branch.','Former staff: disable access immediately.']},
 {id:'branches',title:'Branches & Locations',icon:Building2,purpose:'Represent the physical organisation of the business.',actions:['Create branch.','Create terminal/counter.','Create stock locations.','Assign staff to branches.'],fields:['Branch name','Address / identity','Terminal','Stock location','User assignment'],rules:['Avoid duplicate branches/locations.','Use real physical locations for stock movement.'],access:'Owner/Administrator or authorised settings roles.',troubleshooting:['Wrong branch data: check user assignment and transaction branch.','Stock in wrong place: use Move Stock, not correction.']},
 {id:'settings',title:'Settings & Branding',icon:Settings,purpose:'Configure business-wide defaults so operational users do not have to make repeated decisions.',actions:['Update business profile.','Upload logo/branding.','Configure receipt/bill/printer rules.','Set tax/service defaults.','Configure restaurant setup/policies.','Review security settings.'],fields:['Business identity','Currency','Logo','Document settings','Printer profile','Tax/service charge','Restaurant policies'],rules:['Daily operators should not change global settings during normal transactions.','Use approved business branding on generated documents.'],access:'Owner, Administrator or settings-management permission.',troubleshooting:['Branding not showing: verify saved business branding and generated document settings.','Wrong default tax/service: correct Settings, not each sale.']},
 {id:'printing',title:'Printing & Documents',icon:Printer,purpose:'Generate consistent business documents with references, branding and traceability.',actions:['Generate receipt/bill.','Print/reprint KOT.','Download report PDF.','Use reprint/document history where available.'],fields:['Business logo/name','Document title','Reference','Date','Branch','Prepared by','Totals / detailed rows'],rules:['Generated documents are the source of truth for printing.','Do not recreate a transaction merely to print it again.'],access:'Available where the source transaction/document is permitted.',troubleshooting:['PDF blocked: allow downloads and confirm session.','Wrong branding: review document/branding settings.']},
 {id:'troubleshooting',title:'Troubleshooting & Support',icon:HelpCircle,purpose:'Investigate safely before making corrections or repeating financial actions.',actions:['Record screen and exact action.','Capture time, branch and reference number.','Read visible error message.','Check source history.','Contact support with evidence when unresolved.'],fields:['Screen / module','Time','Branch','User','Reference number','Error message','Screenshot'],rules:['Do not repeatedly retry a financial action when you are unsure whether it posted.','Do not hide discrepancies with stock/cash corrections before investigation.'],access:'Everyone can gather evidence; corrective actions still depend on permissions.',troubleshooting:['Always identify the original source transaction first.','Use Stock History, journal source references, Sales History and shift records as appropriate.']}
]

export default function Documentation({onBack}:{onBack?:()=>void}){
 const [query,setQuery]=useState('')
 const [active,setActive]=useState('overview')
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return docs;return docs.filter(d=>JSON.stringify(d).toLowerCase().includes(q))},[query])
 const current=filtered.find(x=>x.id===active)||filtered[0]||docs[0]
 const Icon=current.icon
 return <div className="min-h-screen bg-[#F4F6F8] text-slate-900">
  <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur">
   <div className="mx-auto flex h-16 max-w-[1460px] items-center gap-3 px-4 sm:px-6">
    <MauzoLogo/>
    <div className="hidden h-7 w-px bg-slate-200 sm:block"/>
    <div className="hidden sm:block"><div className="text-[12px] font-bold text-slate-800">Documentation</div><div className="text-[11px] text-slate-500">Product reference</div></div>
    <div className="ml-auto">{onBack&&<button onClick={onBack} className="ui-btn"><ArrowLeft size={15}/>Back</button>}</div>
   </div>
  </header>

  <div className="border-b border-slate-200 bg-white">
   <div className="mx-auto flex max-w-[1460px] flex-wrap items-center gap-2 px-4 py-3 sm:px-6">
    <a href="/sop" className="rounded-lg px-3 py-2 text-[12px] font-semibold text-slate-600 hover:bg-slate-50">SOP</a>
    <a href="/training" className="rounded-lg px-3 py-2 text-[12px] font-semibold text-slate-600 hover:bg-slate-50">Training Manual</a>
    <a href="/docs" className="rounded-lg bg-slate-950 px-3 py-2 text-[12px] font-semibold text-white">Documentation</a>
    <div className="ml-auto relative w-full sm:w-72"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documentation" className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-[13px] outline-none focus:border-[var(--brand-primary)]"/></div>
   </div>
  </div>

  <div className="mx-auto grid max-w-[1460px] gap-5 px-4 py-5 sm:px-6 lg:grid-cols-[270px_minmax(0,1fr)]">
   <aside className="lg:sticky lg:top-[132px] lg:self-start">
    <div className="rounded-xl border border-slate-200 bg-white p-2 shadow-sm">
     <div className="px-3 pb-2 pt-2 text-[11px] font-bold uppercase tracking-[.08em] text-slate-400">Reference</div>
     <div className="max-h-[calc(100vh-180px)] overflow-y-auto">{filtered.map(d=>{const I=d.icon;return <button key={d.id} onClick={()=>setActive(d.id)} className={'mb-0.5 flex w-full items-center gap-2.5 rounded-lg px-3 py-2.5 text-left text-[12px] font-semibold '+(current.id===d.id?'bg-[var(--brand-soft)] text-[var(--brand-primary)]':'text-slate-600 hover:bg-slate-50')}><I size={16}/><span className="truncate">{d.title}</span></button>})}</div>
    </div>
   </aside>

   <main>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
     <div className="border-b border-slate-100 px-5 py-5 sm:px-6">
      <div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[var(--brand-soft)] text-[var(--brand-primary)]"><Icon size={20}/></div><div><div className="text-[11px] font-bold uppercase tracking-[.1em] text-[var(--brand-primary)]">Reference</div><h1 className="mt-1 text-[24px] font-bold tracking-[-.025em] text-slate-950">{current.title}</h1><p className="mt-1 text-[13px] leading-6 text-slate-600">{current.purpose}</p></div></div>
     </div>
     <div className="grid gap-4 p-5 sm:p-6 xl:grid-cols-2">
      <DocCard title="Main actions" items={current.actions} tone="plain"/>
      <DocCard title="Key fields" items={current.fields} tone="plain"/>
      <DocCard title="Rules & behaviour" items={current.rules} tone="amber"/>
      <DocCard title="Troubleshooting" items={current.troubleshooting} tone="blue"/>
      <div className="xl:col-span-2 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><div className="text-[12px] font-bold text-emerald-800">Access</div><p className="mt-1.5 text-[13px] leading-6 text-emerald-900">{current.access}</p></div>
     </div>
    </section>
   </main>
  </div>
 </div>
}

function DocCard({title,items,tone}:{title:string;items:string[];tone:'plain'|'amber'|'blue'}){
 const c=tone==='amber'?'border-amber-100 bg-amber-50 text-amber-950':tone==='blue'?'border-blue-100 bg-blue-50 text-blue-950':'border-slate-200 bg-white text-slate-700'
 return <div className={'rounded-xl border p-4 '+c}><h2 className="text-[12px] font-bold">{title}</h2><div className="mt-3 grid gap-2">{items.map((x,i)=><div key={x} className="grid grid-cols-[24px_1fr] gap-2 text-[13px] leading-5"><span className="grid h-6 w-6 place-items-center rounded-md bg-white/80 text-[10px] font-bold text-slate-500 ring-1 ring-black/5">{i+1}</span><span>{x}</span></div>)}</div></div>
}
