import { useEffect, useMemo, useState } from 'react'
import { Activity, Boxes, CalendarClock, ChefHat, CircleDollarSign, ClipboardList, Download, Eye, FileText, History, Package, Plus, Printer, ReceiptText, RefreshCw, ShieldCheck, ShoppingCart, Truck, UsersRound, UtensilsCrossed, WalletCards } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, downloadFile, money, nice, openPdf } from '../api'
import { Badge, DataTable, Modal, Panel, Stat, Loading } from '../components'

const types=[
 ['financial','Financial Summary'],['sales','Sales Detail'],['restaurant','Restaurant Operations'],['counters','Sales by Counter / Bar'],['payments','Payment Reconciliation'],['cash_flow','Cash Flow'],['expenses','Expense & Cash-Out'],['allowances','Employee Allowances'],['inventory','Stock On Hand & Valuation'],['stock','Stock Movement'],['stock_counts','Stock Count Variance'],['stock_transfers','Stock Transfers'],['reorder','Reorder Report'],['lot_movement','Batch / Lot Movement'],['inventory_reconciliation','Inventory vs Accounts'],['expiry','Stock Expiry'],['food','Food Consumption & Wastage'],['purchases','Purchases'],['refunds','Refunds & Voids'],['kitchen','Kitchen Performance'],['shifts','Shift Reconciliation'],['ledger','General Ledger'],
] as const
type Section='overview'|'modules'|'activity'|'exports'|'menu'|'schedules'
const sections:[Section,string][]=[['overview','Executive'],['modules','Module Dashboards'],['activity','Activity'],['exports','Report Centre'],['menu','Menu Engineering'],['schedules','Scheduled Delivery']]

export default function Reports({currency,go}:{currency:string;go?:(v:any)=>void}){
 const [summary,setSummary]=useState<any|null>(null),[dash,setDash]=useState<any|null>(null),[activity,setActivity]=useState<any[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[type,setType]=useState('sales'),[busy,setBusy]=useState(''),[branches,setBranches]=useState<any[]>([]),[branchId,setBranchId]=useState('')
 const [detail,setDetail]=useState<any|null>(null),[detailError,setDetailError]=useState(''),[expiryDays,setExpiryDays]=useState('30')
 const [section,setSection]=useState<Section>('overview'),[engineering,setEngineering]=useState<any[]>([]),[schedules,setSchedules]=useState<any[]>([]),[scheduleOpen,setScheduleOpen]=useState(false),[scheduleBusy,setScheduleBusy]=useState(false)
 const [schedule,setSchedule]=useState<any>({reportType:'daily_operations',cadence:'daily',sendTime:'23:59',recipients:''})
 const qs=useMemo(()=>new URLSearchParams({...(from?{from}:{}),...(to?{to}:{}),...(branchId?{branchId}:{})}).toString(),[from,to,branchId])
 const load=()=>Promise.all([api('/reports/summary'+(qs?'?'+qs:'')),api('/reports/management-dashboard'+(qs?'?'+qs:''))]).then(([s,d])=>{setSummary(s);setDash(d)})
 useEffect(()=>{load()},[qs])
 useEffect(()=>{api('/branches').then(setBranches).catch(()=>setBranches([]));api('/scheduled-reports').then(x=>setSchedules(Array.isArray(x)?x:[])).catch(()=>setSchedules([]))},[])
 useEffect(()=>{if(section==='menu')api('/reports/menu-engineering'+(qs?'?'+qs:'')).then(x=>setEngineering(Array.isArray(x)?x:[])).catch(()=>setEngineering([]));if(section==='activity')api('/reports/activity?limit=250').then(x=>setActivity(Array.isArray(x)?x:[])).catch(()=>setActivity([]))},[section,qs])
 const detailedTypes=new Set(['financial','sales','restaurant','counters','payments','cash_flow','expenses','allowances','inventory','stock','stock_counts','stock_transfers','reorder','lot_movement','inventory_reconciliation','expiry','food','purchases','refunds','kitchen','shifts','ledger'])
 const loadDetail=()=>{if(!detailedTypes.has(type)){setDetail(null);setDetailError('');return Promise.resolve()}setDetailError('');setDetail(null);const q=new URLSearchParams({type,...(from?{from}:{}),...(to?{to}:{}),...(branchId?{branchId}:{}),...(type==='expiry'?{expiryDays}: {})}).toString();return api('/accounting/reporting?'+q).then(setDetail).catch((e:any)=>setDetailError(e?.message||'Report could not be loaded'))}
 useEffect(()=>{if(section==='exports')loadDetail()},[section,type,qs,expiryDays])
 async function exp(format:'xlsx'|'csv'|'pdf'){setBusy(format);try{const p='/reports/export?report='+encodeURIComponent(type)+(from?'&from='+from:'')+(to?'&to='+to:'')+(branchId?'&branchId='+branchId:'')+'&format='+format;await downloadFile(p)}finally{setBusy('')}}
 async function detailExp(format:'xlsx'|'csv'|'pdf'){setBusy(format);try{const p='/accounting/reporting/export?type='+encodeURIComponent(type)+(from?'&from='+from:'')+(to?'&to='+to:'')+(branchId?'&branchId='+branchId:'')+(type==='expiry'?'&expiryDays='+expiryDays:'')+'&format='+format;await downloadFile(p)}finally{setBusy('')}}
 async function createSchedule(){const recipients=String(schedule.recipients||'').split(/[;,\n]/).map(x=>x.trim()).filter(Boolean);if(!recipients.length)return;setScheduleBusy(true);try{const x=await api('/scheduled-reports',{method:'POST',body:JSON.stringify({...schedule,recipients})});setSchedules(v=>[...v,x]);setScheduleOpen(false);setSchedule({reportType:'daily_operations',cadence:'daily',sendTime:'23:59',recipients:''})}finally{setScheduleBusy(false)}}
 async function toggleSchedule(x:any){const u=await api('/scheduled-reports/'+x.id,{method:'PUT',body:JSON.stringify({active:!x.active})});setSchedules(v=>v.map(s=>s.id===x.id?u:s))}
 if(!summary||!dash)return <Loading/>
 const netSales=Number(dash.sales?.total||0)-Number(dash.refunds?.total||0),avgCheck=Number(dash.sales?.count||0)?Number(dash.sales.total)/Number(dash.sales.count):0
 return <div>
  <div className="mb-2.5">
   <div className="ui-eyebrow">Reports</div>
   <h2 className="ui-page-title">Reports & Analytics</h2>
  </div>
  <div className="mb-3 max-w-full overflow-x-auto">
   <div className="inline-flex min-w-max gap-0.5 rounded-lg border border-slate-200 bg-white p-0.5">{sections.map(([v,n])=><button key={v} onClick={()=>setSection(v)} className={'shrink-0 rounded-md px-3 py-1.5 text-[10px] font-semibold '+(section===v?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-50')}>{n}</button>)}</div>
  </div>

  {section==='overview'&&<Executive dash={dash} currency={currency} netSales={netSales} avgCheck={avgCheck}/>}
  {section==='modules'&&<Modules dash={dash} currency={currency}/>}
  {section==='activity'&&<ActivityExplorer rows={activity}/>}
  {section==='exports'&&<ReportCentre go={go} type={type} setType={setType} exp={exp} busy={busy} detail={detail} error={detailError} currency={currency} expiryDays={expiryDays} setExpiryDays={setExpiryDays} reload={loadDetail} detailExp={detailExp} from={from} to={to} branchId={branchId} branches={branches} setFrom={setFrom} setTo={setTo} setBranchId={setBranchId}/>}
  {section==='menu'&&<Panel title="Menu Engineering" sub="Popularity, food cost and contribution margin by item.">{engineering.length?<DataTable head={['Item','Category','Units','Revenue','COGS','Contribution','Food Cost','Class']} rows={engineering.map(x=>[<b>{x.product_name}</b>,x.category,Number(x.units),money(x.revenue,currency),money(x.cogs,currency),money(x.contribution,currency),Number(x.food_cost_percent).toFixed(1)+'%',<Badge tone={x.classification==='Star'?'green':x.classification==='Workhorse'?'blue':x.classification==='Puzzle'?'amber':'slate'}>{x.classification}</Badge>])}/>:<Empty icon={UtensilsCrossed} text="No menu sales in this period."/>}</Panel>}
  {section==='schedules'&&<Panel title="Scheduled Management Reports" sub="Daily, weekly and monthly report delivery." action={<button onClick={()=>setScheduleOpen(true)} className="rounded-lg bg-[var(--brand-primary)] px-3 py-2 text-[10.5px] font-semibold text-white"><Plus size={13} className="mr-1 inline"/>Schedule</button>}>{schedules.length?<DataTable head={['Report','Cadence','Time','Recipients','Status','']} rows={schedules.map(x=>[nice(x.report_type),nice(x.cadence),String(x.send_time||'').slice(0,5),(x.recipients||[]).join(', '),<Badge tone={x.active?'green':'slate'}>{x.active?'Active':'Paused'}</Badge>,<button onClick={()=>toggleSchedule(x)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[9.5px] font-medium">{x.active?'Pause':'Enable'}</button>])}/>:<Empty icon={CalendarClock} text="No scheduled reports yet."/>}</Panel>}

  {scheduleOpen&&<Modal title="Schedule Report Delivery" onClose={()=>!scheduleBusy&&setScheduleOpen(false)} size="md"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-medium text-slate-600">Report<select className="control" value={schedule.reportType} onChange={e=>setSchedule({...schedule,reportType:e.target.value})}><option value="daily_operations">Daily Operations</option><option value="financial">Financial Summary</option><option value="sales">Sales Detail</option><option value="restaurant">Restaurant Operations</option><option value="payments">Payments</option><option value="inventory">Inventory</option><option value="cash">Cash & Shifts</option><option value="expenses">Expenses</option><option value="refunds">Refunds & Voids</option><option value="purchases">Purchases</option><option value="stock_movements">Stock Movements</option><option value="kitchen">Kitchen Performance</option></select></label><label className="text-[11px] font-medium text-slate-600">Cadence<select className="control" value={schedule.cadence} onChange={e=>setSchedule({...schedule,cadence:e.target.value})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="text-[11px] font-medium text-slate-600">Send time<input type="time" className="control" value={schedule.sendTime} onChange={e=>setSchedule({...schedule,sendTime:e.target.value})}/></label><label className="text-[11px] font-medium text-slate-600">Recipients<input className="control" value={schedule.recipients} onChange={e=>setSchedule({...schedule,recipients:e.target.value})} placeholder="owner@example.com, manager@example.com"/></label></div><button onClick={createSchedule} disabled={scheduleBusy||!String(schedule.recipients).trim()} className="mt-4 w-full rounded-lg bg-[var(--brand-primary)] py-3 text-[12px] font-semibold text-white disabled:opacity-40">{scheduleBusy?'Saving…':'Save Schedule'}</button></Modal>}
 </div>
}

function Executive({dash,currency,netSales,avgCheck}:{dash:any;currency:string;netSales:number;avgCheck:number}){
 return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Net sales" value={money(netSales,currency)} sub={(dash.sales?.count||0)+' receipts · '+money(dash.refunds?.total,currency)+' refunded'} icon={CircleDollarSign}/><Stat label="Restaurant" value={money(dash.restaurant?.total,currency)} sub={(dash.restaurant?.count||0)+' orders · '+(dash.restaurant?.covers||0)+' covers'} icon={UtensilsCrossed} tone="blue"/><Stat label="Average check" value={money(avgCheck,currency)} sub={Number(dash.restaurant?.covers||0)?money(Number(dash.restaurant.total||0)/Number(dash.restaurant.covers),currency)+' per cover':'No covers'} icon={ReceiptText} tone="violet"/><Stat label="Inventory value" value={money(dash.inventory?.valuation,currency)} sub={(dash.inventory?.low_stock||0)+' low-stock products'} icon={Boxes} tone="amber"/></div>
 <div className="mt-4 grid gap-4 xl:grid-cols-[1.6fr_1fr]"><Panel title="Sales, expenses & refunds trend" sub="Daily management movement for the selected period"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dash.trend||[]}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="d" tickFormatter={(v:any)=>String(v).slice(5,10)} tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip formatter={(v:any)=>money(v,currency)}/><Area type="monotone" dataKey="sales" stroke="currentColor" fill="currentColor" fillOpacity={.08}/><Area type="monotone" dataKey="expenses" stroke="currentColor" fill="currentColor" fillOpacity={.03}/><Area type="monotone" dataKey="refunds" stroke="currentColor" fill="currentColor" fillOpacity={.02}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Payment mix" sub="Tender collections"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={dash.paymentMix||[]} layout="vertical"><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" tick={{fontSize:9}}/><YAxis type="category" dataKey="payment_method" width={90} tick={{fontSize:9}}/><Tooltip formatter={(v:any)=>money(v,currency)}/><Bar dataKey="total" fill="currentColor" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></Panel></div>
 <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Branch performance" sub="Revenue and transaction distribution by branch"><DataTable head={['Branch','Transactions','Sales']} rows={(dash.branches||[]).map((x:any)=>[<b>{x.name}</b>,x.transactions,money(x.sales,currency)])}/></Panel><Panel title="Top items" sub="Revenue, cost and contribution"><DataTable head={['Item','Qty','Revenue','COGS','Contribution']} rows={(dash.topItems||[]).map((x:any)=>[<b>{x.product_name}</b>,x.qty,money(x.revenue,currency),money(x.cogs,currency),money(x.contribution,currency)])}/></Panel></div></>
}
function Modules({dash,currency}:{dash:any;currency:string}){
 const cards=[
  ['POS & Sales',ShoppingCart,dash.sales?.count+' transactions',money(dash.sales?.total,currency),'Discounts '+money(dash.sales?.discount,currency)],
  ['Restaurant',UtensilsCrossed,dash.restaurant?.count+' orders',money(dash.restaurant?.total,currency),(dash.restaurant?.covers||0)+' covers'],
  ['Kitchen',ChefHat,dash.kitchen?.tickets+' tickets',Number(dash.kitchen?.avg_minutes||0).toFixed(1)+' min avg','Preparation performance'],
  ['Inventory',Package,dash.inventory?.products+' products',money(dash.inventory?.valuation,currency),(dash.inventory?.low_stock||0)+' low stock'],
  ['Production',ClipboardList,dash.production?.count+' batches',String(dash.production?.yield||0)+' yield','Cost '+money(dash.production?.cost,currency)],
  ['Purchasing',Truck,dash.purchases?.count+' POs',money(dash.purchases?.total,currency),'Approved/active purchasing'],
  ['Payments',WalletCards,dash.payments?.count+' payments',money(dash.payments?.total,currency),'Collected tenders'],
  ['Refunds & Voids',RefreshCw,dash.refunds?.count+' approved',money(dash.refunds?.total,currency),'Controlled reversals'],
  ['Expenses',ReceiptText,dash.expenses?.count+' expenses',money(dash.expenses?.total,currency),'Ledger-posted costs'],
  ['Tables',UtensilsCrossed,dash.tables?.total+' tables',(dash.tables?.occupied||0)+' occupied',(dash.tables?.dirty||0)+' dirty'],
  ['Customers',UsersRound,dash.customers?.count+' customers',money(dash.customers?.receivable,currency),'Outstanding receivables'],
  ['Staff',UsersRound,dash.staff?.count+' active','Access controlled','Activity audit enabled'],
 ]
 return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([name,Icon,primary,secondary,sub]:any)=><div key={name} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-600"><Icon size={15}/></div><b className="text-[12px]">{name}</b></div><div className="mt-4 text-[17px] font-semibold text-slate-900">{secondary}</div><div className="mt-1 text-[10.5px] text-slate-500">{primary}</div><div className="mt-3 border-t border-slate-100 pt-2 text-[9.5px] text-slate-400">{sub}</div></div>)}</div>
}
function ActivityExplorer({rows}:{rows:any[]}){return <Panel title="Management Activity Explorer" sub="Who did what, to which record, and when. Use entity/reference IDs to trace into operational records.">{rows.length?<DataTable head={['Time','User','Module','Action','Record','Details']} rows={rows.map(x=>[new Date(x.created_at).toLocaleString(),x.user_email||'System',nice(x.entity||'system'),<Badge tone="blue">{nice(x.action)}</Badge>,x.entity_id||'-',<div className="max-w-[360px] truncate text-[10px] text-slate-500">{compact(x.details)}</div>])}/>:<Empty icon={Activity} text="No activity found."/>}</Panel>}
function ReportCentre({go,type,setType,exp,busy,detail,error,currency,expiryDays,setExpiryDays,reload,detailExp,from,to,branchId,branches,setFrom,setTo,setBranchId}:{go?:(v:any)=>void;type:string;setType:(v:string)=>void;exp:(v:'xlsx'|'csv'|'pdf')=>void;busy:string;detail:any;error:string;currency:string;expiryDays:string;setExpiryDays:(v:string)=>void;reload:()=>Promise<any>;detailExp:(v:'xlsx'|'csv'|'pdf')=>Promise<void>;from:string;to:string;branchId:string;branches:any[];setFrom:(v:string)=>void;setTo:(v:string)=>void;setBranchId:(v:string)=>void}){
 const detailed=new Set(['financial','sales','restaurant','counters','payments','cash_flow','expenses','allowances','inventory','stock','stock_counts','stock_transfers','reorder','lot_movement','inventory_reconciliation','expiry','food','purchases','refunds','kitchen','shifts','ledger']).has(type)
 const [tx,setTx]=useState<any|null>(null),[txOpen,setTxOpen]=useState(false),[txBusy,setTxBusy]=useState(false)
 async function openTransaction(row:any){if(!row?.id)return;setTxBusy(true);try{setTx(await api('/sales/'+row.id));setTxOpen(true)}finally{setTxBusy(false)}}
 function csv(){
  if(!detail?.rows?.length)return
  const cols=detail.columns||[],esc=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"'
  const data=[cols.map((x:any)=>esc(x[1])).join(','),...detail.rows.map((r:any)=>cols.map((x:any)=>esc(formatCell(r[x[0]],x[0],currency))).join(','))].join('\n')
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));a.download='MauzoPOS-'+type+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)
 }
 return <div className="space-y-4">
  <Panel title="Report Centre" sub="Choose the report first, then filter the exact period and branch.">
   <div className="max-w-[980px]">
    <div className="flex flex-wrap items-end gap-2">
     <label className="ui-label">Report<select className="ui-control mt-1 w-[270px]" value={type} onChange={e=>setType(e.target.value)}>{types.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>
     {type==='expiry'&&<label className="ui-label">Expiry window<select className="ui-control mt-1 w-[140px]" value={expiryDays} onChange={e=>setExpiryDays(e.target.value)}><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="3650">All dated stock</option></select></label>}
    </div>

    <div className="mt-3 border-t border-slate-100 pt-3">
     <div className="mb-1.5 ui-section-label">Filter this report</div>
     <div className="flex flex-wrap items-end gap-2">
      <label className="ui-label">From<input type="date" className="ui-control mt-1 w-[160px]" value={from} onChange={e=>setFrom(e.target.value)}/></label>
      <label className="ui-label">To<input type="date" className="ui-control mt-1 w-[160px]" value={to} onChange={e=>setTo(e.target.value)}/></label>
      <label className="ui-label">Branch<select className="ui-control mt-1 w-[180px]" value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
      <div className="flex flex-wrap gap-2 pb-[1px]">{detailed?<><button onClick={()=>reload()} className="ui-btn"><RefreshCw size={13}/>Generate</button><button onClick={()=>detailExp('xlsx')} className="ui-btn ui-btn-primary"><Download size={13}/>{busy==='xlsx'?'Preparing…':'Excel'}</button><button onClick={csv} className="ui-btn"><Download size={13}/>CSV</button><button onClick={()=>detailExp('pdf')} className="ui-btn"><Printer size={14}/>{busy==='pdf'?'Downloading…':'Download PDF'}</button></>:<><button onClick={()=>exp('xlsx')} className="ui-btn ui-btn-primary"><Download size={13}/>{busy==='xlsx'?'Preparing…':'Excel'}</button><button onClick={()=>exp('csv')} className="ui-btn">CSV</button><button onClick={()=>exp('pdf')} className="ui-btn"><Printer size={14}/>{busy==='pdf'?'Downloading…':'Download PDF'}</button></>}</div>
     </div>
    </div>
   </div>
  </Panel>
  {detailed&&error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-[11px] text-red-700">{error}</div>}
  {detailed&&!error&&!detail&&<Loading/>}
  {detailed&&detail&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(detail.summary||{}).map(([k,v]:any)=><Stat key={k} label={nice(k)} value={typeof v==='number'&&/sales|profit|cogs|cash|amount|value|expense|allowance|net|debit|credit|expected|actual|variance|purchases|wastage|consumption/i.test(k)?money(v,currency):String(v)} sub="Filtered report total" icon={ReceiptText}/>)}</div><Panel title={detail.title||'Detailed Report'} sub={(detail.rows?.length||0)+' source-level rows · filtered to the selected date and branch'}>{detail.rows?.length?<DataTable head={[...(detail.columns||[]).map((x:any)=>x[1]),...(type==='sales'?['Audit']:[])]} rows={detail.rows.map((r:any)=>[...(detail.columns||[]).map((x:any)=>formatCell(r[x[0]],x[0],currency)),...(type==='sales'?[<button disabled={txBusy} onClick={()=>openTransaction(r)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10.5px] font-medium text-slate-700 hover:border-[var(--brand-border)] hover:text-[var(--brand-primary)]"><Eye size={13}/>Open</button>]:[])])}/>:<Empty icon={ClipboardList} text="No records match these filters."/>}</Panel></>}
  {txOpen&&tx&&<Modal title={'Transaction · '+tx.sale.receipt_no} onClose={()=>setTxOpen(false)} size="xl">
    <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3">
      <div><div className="text-[10px] uppercase tracking-[.08em] text-slate-400">Receipt</div><div className="mt-0.5 text-[16px] font-semibold text-slate-900">{tx.sale.receipt_no}</div><div className="mt-0.5 text-[10.5px] text-slate-500">{new Date(tx.sale.created_at).toLocaleString()} · {tx.sale.branch_name||'Branch'} · {tx.sale.cashier||'User'}</div></div>
      <div className="flex gap-2"><button onClick={()=>openPdf('/documents/sale/'+tx.sale.id+'/pdf')} className="ui-btn"><FileText size={13}/>Receipt PDF</button>{go&&<button onClick={()=>{setTxOpen(false);go('Sales')}} className="ui-btn ui-btn-primary"><ShieldCheck size={13}/>Refund / Void / Correct</button>}</div>
    </div>
    <div className="mt-3 grid gap-3 sm:grid-cols-4"><Mini label="Total" value={money(tx.sale.total,currency)}/><Mini label="Paid" value={money(tx.sale.amount_paid,currency)}/><Mini label="Balance" value={money(tx.sale.balance_due,currency)}/><Mini label="Refunded" value={money(tx.sale.refunded_amount,currency)}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <Panel title="Items" sub="Original transaction lines"><DataTable head={['Item','Qty','Unit','Total']} rows={(tx.items||[]).map((x:any)=>[x.product_name,Number(x.qty),money(x.unit_price,currency),money(x.line_total,currency)])}/></Panel>
      <Panel title="Tender history" sub="Posted payments allocated to this transaction">{(tx.payments||[]).length?<DataTable head={['Method','Reference','Amount']} rows={tx.payments.map((x:any)=>[nice(x.payment_method),x.reference||'-',money(x.allocated_amount||x.amount,currency)])}/>:<div className="py-8 text-center text-[11px] text-slate-400">No posted tenders.</div>}</Panel>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <Panel title="Accounting postings" sub="Journal entries generated from this transaction">{(tx.journals||[]).length?<DataTable head={['Date','Journal','Description','Debit','Credit','Status']} rows={tx.journals.map((x:any)=>[String(x.entry_date).slice(0,10),x.entry_no,x.description,money(x.debit,currency),money(x.credit,currency),<Badge tone={x.is_reversed?'amber':'green'}>{x.is_reversed?'Reversed':nice(x.status)}</Badge>])}/>:<div className="py-8 text-center text-[11px] text-slate-400">No linked journal posting found.</div>}</Panel>
      <Panel title="Corrections & approvals" sub="Refunds, voids and approved adjustments remain traceable">{[...(tx.adjustments||[]).map((x:any)=>({kind:nice(x.adjustment_type),ref:x.reference_no,status:x.status,reason:x.reason,amount:x.requested_amount})),...(tx.refunds||[]).map((x:any)=>({kind:nice(x.request_kind),ref:x.refund_no,status:x.status,reason:x.reason,amount:x.total}))].length?<DataTable head={['Type','Reference','Reason','Amount','Status']} rows={[...(tx.adjustments||[]).map((x:any)=>({kind:nice(x.adjustment_type),ref:x.reference_no,status:x.status,reason:x.reason,amount:x.requested_amount})),...(tx.refunds||[]).map((x:any)=>({kind:nice(x.request_kind),ref:x.refund_no,status:x.status,reason:x.reason,amount:x.total}))].map((x:any)=>[x.kind,x.ref,x.reason||'-',money(x.amount,currency),<Badge tone={x.status==='approved'?'green':x.status==='rejected'?'red':'amber'}>{nice(x.status)}</Badge>])}/>:<div className="py-8 text-center text-[11px] text-slate-400">No corrections or approval requests.</div>}</Panel>
    </div>
    <div className="mt-4"><Panel title="Audit trail" sub="Who changed, approved, refunded or reversed this transaction and when">{(tx.audit||[]).length?<DataTable head={['Time','User','Action','Record','Details']} rows={tx.audit.map((x:any)=>[new Date(x.created_at).toLocaleString(),x.user_email||'System',nice(x.action),nice(x.entity)+(x.entity_id?' · '+x.entity_id:''),<div className="max-w-[420px] truncate text-[10px] text-slate-500">{compact(x.details)}</div>])}/>:<div className="py-8 text-center text-[11px] text-slate-400">No audit events recorded for this transaction.</div>}</Panel></div>
    <div className="mt-4 rounded-xl border border-[var(--brand-border)] bg-[var(--brand-soft)] p-3 text-[11px] leading-5 text-slate-700"><History size={14} className="mr-1 inline text-[var(--brand-primary)]"/>Posted transactions are not silently edited. Corrections are made through controlled refund, void or reversal actions so the original entry and the correction remain auditable.</div>
  </Modal>}
 </div>
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-200 bg-white p-3"><div className="text-[9.5px] uppercase tracking-[.08em] text-slate-400">{label}</div><div className="mt-1 text-[14px] font-semibold text-slate-900">{value}</div></div>}
function formatCell(v:any,key:string,currency:string){if(v==null||v==='')return '-';if(typeof v==='number'){return /amount|total|sales|profit|cogs|cash|cost|value|debit|credit|balance|tax|discount|purchases|wastage|consumption|expected|actual|variance/i.test(key)?money(v,currency):v}if(/_at$|date/.test(key)){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toLocaleString()}return nice(String(v))}
function Empty({icon:Icon,text}:{icon:any;text:string}){return <div className="py-10 text-center text-[11px] text-slate-400"><Icon size={18} className="mx-auto mb-2"/>{text}</div>}
function compact(v:any){if(!v)return '-';try{return Object.entries(typeof v==='string'?JSON.parse(v):v).slice(0,5).map(([k,x])=>nice(k)+': '+String(x)).join(' · ')}catch{return String(v)}}
